### PR TITLE
Use the first element in carousel for carousel height adjustment

### PR DESCRIPTION
**Pull request by ddmail2009**
Instead of hard-code the container/carousel height, copy a hidden non-absolute
positioning photo for CSS height adjustment.

Instead of 90/10% split of the photo/caption section, use flex-grow
instead.

### CODE REVIEW

**Review by HC-Hwang — COMMENTED** [review]
I found 75vh works better, especially for iPhone version. 

The figures in photo gallery are still a bit small (don't fill the container completely?). Also, can we make the horizontal photos larger?

**Comment by ddmail2009** [comment]
because photo carousel are mixed with horizontal and vertical photos.

We can make horizontal bigger but then vertical photos will be smaller.

**Comment by ddmail2009** [comment]
If the photo inside photo carousel is too small, then how about display fewer items in small screen?

**Comment by HC-Hwang** [comment]
Yeah fewer items sound good (either in general or only on smaller screens).
As you said, maybe we can also try make horizontal photos a bit larger in size. I feel the heights of the horizontal photos should not be too small compared to the heights of the vertical photos.

**Comment by ddmail2009** [comment]
both vertical and horizontal photos has the the same width, the height is then adjusted correspondingly to preserve the ratio.

The issue you think vertical is larger is simply because phone in general is vertical.   If you rotate your phone then you'll think the vertical is the smaller one.

**Comment by HC-Hwang** [comment]
But same widths mean that the horizontal photos are smaller. Or maybe we just set them to be the same sizes?

**Comment by ddmail2009** [comment]
what do you mean by same size?  both horizontal and vertical photos set to same 400x300 for example?  then we lost the ratio and I don't think that's what you r referring to.

**Comment by HC-Hwang** [comment]
By same size I mean, if vertical is 400*300, the horizontal is 300*400.

**Comment by HC-Hwang** [comment]
Or, more strictly! How about the same area!?

**Comment by ddmail2009** [comment]
Seems like that's why we need photo preprocessing.

**Comment by ddmail2009** [comment]
Or we can set every item in carousel to same size by clipping them?

**Comment by HC-Hwang** [comment]
You mean clip the source files to the same size? Hmmm I prefer maybe we just make the size of horizontal photos a bit larger, say, set their widths to be 1.5 times the widths of vertical photos?

**Comment by ddmail2009** [comment]
> Or, more strictly! How about the same area!?

Mind elaborate? Don't know what do you mean. 

Also how 400x300 and 300x400 fixes the issue?

**Comment by ddmail2009** [comment]
Added another commit to adjust itemsRow in small screen.

**Review by HC-Hwang — APPROVED** [review]
Approved! Thanks!

**Pull request merged**
