### PR TITLE
Use strict mode in JS and jshint ES5 check

### PR DESCRIPTION
**Pull request by ddmail2009**
Run with jshint in https://jshint.com/.

TODO: keyword:class ONLY support in ES6

### CODE REVIEW

**Comment by ddmail2009** [comment]
看起來似乎JS standard要加semicolon

**Review by HC-Hwang — COMMENTED** [review]
What are strict mode and ES5?

**Comment by ddmail2009** [comment]
> What are strict mode and ES5?

ES5 https://www.w3schools.com/js/js_es5.asp
 - JS standard
strict mode https://www.w3schools.com/js/js_strict.asp 
 - forbit undeclared varible.

**Comment by HC-Hwang** [comment]
> 

Okay! Sounds good!

**Review by HC-Hwang — APPROVED** [review]

**Pull request merged**
